### ISSUE TITLE
Simple instructions for installing requirements on ubuntu

### ISSUE THREAD

**Issue by DavidPowell** [robert-dodier/maxima-jupyter#3]
I have used maxima before, but understand almost nothing about the lisp ecosystem behind it. Is there a simple list of `apt-get` commands that I can use to install all the requirements? If so, it would be great to document this explicitly.

**Comment by robert-dodier** [comment]
David, thanks for your interest in Maxima-Jupyter. Unfortunately there isn't any simple way to install all of the requirements, since the version of Maxima that is in the Debian/Ubuntu repositories is compiled with GCL which can't be used with Maxima-Jupyter (as GCL lacks threads). I have, however, compiled a Maxima package which can be installed onto Debian/Ubuntu and which uses Clozure CL (which does have threads so it can be used with Maxima-Jupyter). I am working on clarifying the documentation so that it should be possible to install that package and follow the instructions to get Maxima-Jupyter running.

**Comment by robert-dodier** [comment]
I'm closing this discussion thread since it is more or less impossible to use apt-get to install everything, and even if it's possible I'm unfortunately not making any headway in that direction. But thanks for your interest in Maxima-Jupyter all the same. I'll keep working on it and I hope someday soon I'll have something to report.

**Comment by jlapeyre** [comment]
Here are ubuntu packages of maxima built for several lisps, including sbcl. If you are using debian, there is a tool (google for it) to automatically translate the ubuntu package to a debian package.
https://code.launchpad.net/~maxima-developers/+archive/ubuntu/maxima-nightly
