### ISSUE TITLE
Lisp error: invalid specializer (ORDERED-CONTAINER-MIXIN ARRAY) 

### ISSUE THREAD

**Issue by justineuro** [robert-dodier/maxima-jupyter#34]
While following the instructions for installing the `maxima-jupyter` kernel similar to that described in  [https://github.com/robert-dodier/maxima-jupyter](https://github.com/robert-dodier/maxima-jupyter/) (Method 2), a Lisp error occurred during the installation of `pzmq-20171019-git` (compilation of  files: `grovel.c` and `grovel.grovel-tmp.lisp`).  The error message was:

```
 In method definition for INSERT-SEQUENCE, found an invalid specializer (ORDERED-CONTAINER-MIXIN
                                                                         ARRAY)
```

`jupyter notebook` starts and the `maxima-jupyter` kernel is detected but no connection was attained.

Additional info:  
- OS: Debian 8 (Jessie) LTS (until 2020)
-  `maxima-sage` was used instead of `maxima` (latter was linked to former in `/usr/bin`)
- Please see attached file: [`001bug-maxima-jupyter-20180803.txt`](https://github.com/roswell/quicklisp/files/2256413/001bug-maxima-jupyter-20180803.txt) for more details

Thank you in advance for any help you can give in this regard.

P.S.  A similar error occured when using Method 1.  Please see [002abug-maxima-jupyter-20180803.txt](https://github.com/orivej/pzmq/files/2256569/002abug-maxima-jupyter-20180803.txt).

**Comment by robert-dodier** [comment]
Hi, thanks very much for your interest in Maxima, and for your detailed bug report.

I see that you are working with ECL. Unfortunately I have not been able to get ECL to work with Maxima-Jupyter, and another developer tried it and was not successful. So I recommend using either SBCL or Clozure CL, since those are known to work. I have updated `Readme.md` to describe the situation more clearly.

I'm closing this issue, since to the best of my knowledge, ECL won't work. However, if you try another Lisp and you run into another problem, please feel free to open another issue.
