### ISSUE TITLE
problem maxima-jupter

### ISSUE THREAD

**Issue by jmarcellopereira** [robert-dodier/maxima-jupyter#4]
Hello 
I love the maxima and want to use it in jupyter. But when trying to install the module, this error occurs:
How to solve?

Maxima-Jupyter -- an enhanced interactive Maxima shell 
CL-Jupyter (C) 2014-2015 Frederic Peschanski (cf. LICENSE) 
Additional Maxima-specific stuff by Robert Dodier; thanks Frederic! 

... Frontend: using IPython v4.0 
/home/jmarcellopereira/anaconda3/lib/python3.4/site-packages/IPython/utils/path.py:258: UserWarning: get_ipython_dir has moved to the IPython.paths module 
 warn("get_ipython_dir has moved to the IPython.paths module") 
error: Maxima-Jupyter executable not specified. 
Abort.

**Comment by jmarcellopereira** [comment]
?

**Comment by robert-dodier** [comment]
Sorry, I've been busy with other things.  But I will try to look at this problem soon. Thanks for your interest in maxima-jupyter.

**Comment by jmarcellopereira** [comment]
ok, Dodier, thanks for the feedback ;)

**Comment by robert-dodier** [comment]
The message "error: Maxima-Jupyter executable not specified" occurs because --maxima-jupyter-exec isn't specified when you configure Maxima-Jupyter. Did you follow the installation instructions? Can you try installing it again, and this time copy and paste any and all of the output so that others can see what is going on?

Please bear in mind that I really have no idea what is happening on your computer unless you tell me, as precisely as possible.

**Comment by zockoshi** [comment]
Changing 
`self.ipython_dir = IPython.utils.path.get_ipython_dir()`
to 
`self.ipython_dir = IPython.paths.get_ipython_dir()`
in "install-maxiam-jupyter.py" should help. I can't confirm yet because I wasn't able to create an image with sbcl.

**Comment by robert-dodier** [comment]
I'm closing this discussion thread as there hasn't been any further info. If you're still interested in maxima-jupyter, and I hope you are, please open a new thread.
