### ISSUE TITLE
installing from docker icon, get "Can't reopen file /usr/lib/python3.7/.../codemirror/mode/meta.j"s

### ISSUE THREAD

**Issue by lbrock** [robert-dodier/maxima-jupyter#74]
Robert:
This is on W10, current, probably without any other Maxima, Jupyter components or tools installed.
Here is log from rerun, error message is same as on first run; error message is a few lines up from end:
-------------
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker284o69_j'...
HEAD is now at b233b84 Merge pull request #70 from WetHat/issue57
Using DockerBuildPack builder
Step 1/20 : FROM archlinux/base
 ---> c767d90efdb9
Step 2/20 : ARG NB_USER=mj
 ---> Using cache
 ---> b28cb7a07191
Step 3/20 : ARG NB_UID=1000
 ---> Using cache
 ---> 54e76329d5e9
Step 4/20 : ENV USER ${NB_USER}
 ---> Using cache
 ---> 2476062e1129
Step 5/20 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> feea520d8a16
Step 6/20 : RUN pacman -Syu --noconfirm base-devel jupyter gnuplot maxima &&     useradd --create-home --shell=/bin/false --uid=${NB_UID} ${NB_USER}
 ---> Using cache
 ---> 955ac843ac5c
Step 7/20 : WORKDIR ${HOME}/maxima-jupyter
 ---> Using cache
 ---> 5d56df58ccff
Step 8/20 : COPY . ${HOME}/maxima-jupyter
 ---> ff716031c33b
Step 9/20 : COPY maxima.js /usr/lib/python3.7/site-packages/notebook/static/components/codemirror/mode/maxima
 ---> cf1af956649c
Step 10/20 : COPY maxima_lexer.py /usr/lib/python3.7/site-packages/pygments/lexers
 ---> 69c53319aa2e
Step 11/20 : RUN patch /usr/lib/python3.7/site-packages/notebook/static/components/codemirror/mode/meta.js codemirror-mode-meta-patch &&     patch /usr/lib/python3.7/site-packages/pygments/lexers/_mapping.py pygments-mapping-patch &&     chown -R ${NB_UID} ${HOME} && chgrp -R ${NB_USER} ${HOME}
 ---> Running in e8f1f4308f15
patching file /usr/lib/python3.7/site-packages/notebook/static/components/codemirror/mode/meta.js
Hunk #1 FAILED at 77.
patch: **** Can't reopen file /usr/lib/python3.7/site-packages/notebook/static/components/codemirror/mode/meta.js : No such file or directory
Removing intermediate container e8f1f4308f15
The command '/bin/sh -c patch /usr/lib/python3.7/site-packages/notebook/static/components/codemirror/mode/meta.js codemirror-mode-meta-patch &&     patch /usr/lib/python3.7/site-packages/pygments/lexers/_mapping.py pygments-mapping-patch &&     chown -R ${NB_UID} ${HOME} && chgrp -R ${NB_USER} ${HOME}' returned a non-zero code: 2 
--------

**Comment by robert-dodier** [comment]
Well, it appears the attempt to patch the codemirror stuff has failed, and my first guess about that is that the codemirror files are not in the same place as what's assumed by the patch. I don't really know what to do about that. The syntax highlighting is not crucial so it would be great to just skip over it. However, I don't know how to make the patch optional in the Docker file.

I guess at this point my only advice is to try an installation by hand instead of using Docker. I can try to walk you through it if you want to try it. I don't have a Windows system to experiment with so I don't know what particular issues you might run into.

**Comment by robert-dodier** [comment]
I'm going to close this ticket since it seems to be inactive, but anyway let me mention that I've pushed commit 6b2f51b to remove the CodeMirror and Pygments patches from the Dockerfile, since those are a point of failure and not very important. So if anybody can try it again, I think it's more likely to work.

(Note that I've submitted code for Pygments which will appear in their next release, and created a npm package on npmjs.com to package a CodeMirror mode for Maxima. See: https://www.npmjs.com/package/codemirror-mode-maxima)
