### ISSUE TITLE
Docker image for Jupyter+Maxima

### ISSUE THREAD

**Issue by alessandro-dibella-rockalltech** [robert-dodier/maxima-jupyter#9]
Hi,
I created a simple Dockerfile to build an image based on [Jupyter Notebook Data Science Stack](https://hub.docker.com/r/jupyter/datascience-notebook/) that includes [Maxima](http://maxima.sourceforge.net) and this kernel.

If anybody is interested, it can be found [here](https://gitlab.com/alessandro.dibella/docker/jupyter-maxima).

Thanks

**Comment by robert-dodier** [comment]
Hi Alessandro, Thanks a lot for working on the Docker image! I think that could make it much easier to install Maxima-Jupyter.

However, I can't test it myself because I cannot install Docker. I have a 32 bit laptop but Docker requires 64 bit. Do you have any advice about installing Docker on a 32 bit system? I have asked this question in a Docker forum but didn't receive any reply.

Thanks again for your interest in Maxima-Jupyter, I appreciate it very much.

**Comment by aldib** [comment]
The [Docker Toolbox doumentation](https://docs.docker.com/toolbox/toolbox_install_windows/) specifically states that: *To run Docker, your machine must have a 64-bit operating system running Windows 7 or higher.*. Thus, it's unlikely that you'll find something that works out of the box. Probably your best option is to build docker from source using Linux. Although, it's not exactly what you need, [this site](https://www.nirmata.com/2016/02/09/docker-daemon-for-x32-architectures/) shows a Dockerfile containing the steps required to build the docker daemon on Ubuntu 32 bits. I also found [this article in [stackoverflow](https://stackoverflow.com/a/48881019) that claims success in getting docker to work on  Ubuntu 16.04 32-bit. Sorry for not being more specific but I never faced this problem before.

**Comment by robert-dodier** [comment]
Thanks for the info. I was able to successfully build Docker on my 32 bit system using the instructions given by https://stackoverflow.com/a/48881019. However, when I try to build the jupyter-maxima image, I find that `sudo docker build -t alessandro.dibella/jupyter-maxima:latest .` runs for a long time and then eventually says:

```
Step 2 : RUN apt-get update && 	apt-get -y remove maxima maxima-doc wxmaxima && 	apt-get -y install libzmq3-dev gnuplot
 ---> Running in 73665df06633
exec format error
```

I believe "exec format error" has something to do with 32 bit versus 64 bit -- perhaps there is an assumption in the jupyter-maxima configuration that the system is 64 bits? If you have any suggestions, I would be interested to hear.

**Comment by aldib** [comment]
It could be a problem with the Clozure compiler, I'm using `ccl64` in the Dockerfile. Can you please try to edit the Dockerfile locally and change the 5 occurrences of `ccl64`  to `ccl` before building the image again?
If this doesn't solve the problem, we can troubleshoot each command but let's give this a try first.

**Comment by psychemedia** [comment]
@aldib I'm struggling to get your Dockerfile to run too?

After:

`COPY src/ /usr/local/src/scripts/`

the `RUN` command following it needs to be preceded by something like:

`WORKDIR /usr/local/src/`

otherwise the path is wrong.

I also think that the `quicklisp.lisp` file needs to be added to the `src/lisp` dir?

The [`cl-jupyter/install-cl-jupyter.py'](https://github.com/fredokun/cl-jupyter/blob/master/install-cl-jupyter.py) file tests `config.lisp_implementation` for various values including `sbcl` and `ccl` but not `ccl64`. I kept getting `Can't assign LDT entry` errors trying to use `ccl` in a Linux container, but could run some of the early steps using `ccl64`.

Working step wise, I've got as far as:

```
ccl64 --load ./cl-jupyter.lisp
> Error: There is no package named "ASDF" .
```

Do you have a Github repo anywhere that successfully builds and deploys the Maxima kernel via [Binderhub](https://mybinder.org/)?

**Comment by aldib** [comment]
@psychemedia It's been few months since I last build that image but it was working for me at the time. Unfortunately, I'm completely swamped at work at the moment and I won'r be able to look at it for the next few weeks. I'll post an update here once it's fixed.

**Comment by psychemedia** [comment]
Ok, thanks... 

I started trying to build a simpler one from the build-with-dependency instructions in this repo, but ArchLinux completely new to me and I got stuck trying to build the installation package...

```
### Dockerfile

#Build:
#docker build --tag p/m .
#Peek inside:
#docker run -it --entrypoint=/bin/bash p/m -i


FROM base/archlinux

#https://bbs.archlinux.org/viewtopic.php?id=229027
RUN useradd --create-home --shell=/bin/false build && usermod -L build
RUN echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

WORKDIR /home/build
RUN curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/maxima-jupyter-git.tar.gz && \
    tar -xvf maxima-jupyter-git.tar.gz 

#Install required packages
RUN pacman -Sy --noconfirm  maxima
RUN pacman -Sy --noconfirm  jupyter
RUN pacman -Sy --noconfirm  git
RUN pacman -Sy --noconfirm binutils

RUN pacman -Sy --noconfirm fakeroot

RUN chown -R build maxima-jupyter-git

WORKDIR maxima-jupyter-git

#Copy the kernelspec
RUN mkdir -p /usr/local/share/jupyter/kernels/maxima && cp kernel.json /usr/local/share/jupyter/kernels/maxima

#We can't run makepkg as root?
USER build
RUN makepkg -SCsri

USER root
#Following is broken...
#RUN pacman -U  *.pkg.tar.xz

#CMD ["jupyter", "console", "--kernel=maxima"]

```
