### ISSUE TITLE
mactex-utilities note found

### ISSUE THREAD

**Issue by codmccabe** [robert-dodier/maxima-jupyter#93]
Please help, I am sorry if it is not a good question, but I can't figure out how to get this to work.

```
Maxima 5.44.0 http://maxima.sourceforge.net
using Lisp SBCL 2.0.1.debian
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) load("load-maxima-jupyter.lisp");

file_search1: mactex-utilities not found in file_search_maxima,file_search_lisp
                                                                              .
 -- an error. To debug this try: debugmode(true);
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

**Comment by robert-dodier** [comment]
Hi Michael, it looks like you are working w/ Debian Linux. Did you install Maxima from a package repo (via apt-get)? If so, I think maybe the problem is that the Debian packages separate the core stuff from additional stuff, and mactex-utilities is in the additional stuff. The additional package is named `maxima-share`.

If you get past that error, I think there might be another one, having to do with ASDF (package manager for Common Lisp). I'll refrain from saying more about that for the moment, maybe you can try installing `maxima-share` first.

**Comment by codmccabe** [comment]
I just commented out the mactex and the stringproc. I'll figure out those issues if I need too... Once I commented those two lines out it worked. I forgot that's how I got it to work in the past, and didn't have any issues when using maxima-jupyter in the past.

I installed maxima using the source and sbcl. Sorry don't know if that is the correct terminology.
