### ISSUE TITLE
Maxima-jupyter build failure

### ISSUE THREAD

**Issue by shamazmazum** [robert-dodier/maxima-jupyter#96]
After commit `021cf31` in `common-lisp-jupyter` maxima-jupyter cannot be built:

~~~
(%i1) :lisp (load "load-maxima-jupyter.lisp")
To load "maxima-jupyter":
  Load 1 ASDF system:
    maxima-jupyter
; Loading "maxima-jupyter"
..................................................
[package maxima-jupyter];
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "RENDER" not found in the JUPYTER package.
;
;       Line: 81, Column: 25, File-Position: 2201
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/vasily/maxima-jupyter/src/results.lisp" {1003FBDF83}>
While evaluating the form starting at line 4, column 0
  of
Maxima encountered a Lisp error:

 COMPILE-FILE-ERROR while
 compiling #<CL-SOURCE-FILE "maxima-jupyter" "src" "results">

Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
#P"/home/vasily/maxima-jupyter/load-maxima-jupyter.lisp":
;
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
~~~

The API is broken so hard, so I cannot get it working.

**Comment by yitzchak** [comment]
You need to use the common-lisp-jupyter that is in quicklisp. The git version has changes that I have not made a PR for yet in maxima-jupyter.

**Comment by shamazmazum** [comment]
@yitzchak  Hopefully, I have an old image ;)

**Comment by yitzchak** [comment]
The results branch of [yitzchak/maxima-jupyter](https://github.com/yitzchak/maxima-jupyter/tree/results) is my in progress updates to fix this. When quicklisp updates I'll submit a PR.

**Comment by codmccabe** [comment]
Sorry, I don't understand the fix for this :(
I am trying to install this locally.
Maxima 5.45.1 https://maxima.sourceforge.io
using Lisp SBCL 2.0.1.debian
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) load("load-maxima-jupyter.lisp");
To load "maxima-jupyter":
  Load 1 ASDF system:
    maxima-jupyter
; Loading "maxima-jupyter"
......; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "RENDER" not found in the JUPYTER package.
;   
;       Line: 81, Column: 25, File-Position: 2201
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/mccrack/GitHub/maxima-jupyter/src/results.lisp" {1004943503}>
While evaluating the form starting at line 4, column 0
  of #P"/home/mccrack/GitHub/maxima-jupyter/load-maxima-jupyter.lisp":
; 
; compilation unit aborted
;   caught 3 fatal ERROR conditions
;   caught 1 ERROR condition

loadfile: failed to load load-maxima-jupyter.lisp
 -- an error. To debug this try: debugmode(true);

**Comment by yitzchak** [comment]
@codmccabe You probably need to update your quicklisp distribution and your local copy of Maxima-Jupyter.. In the Maxima-Jupyter folder.
```
git pull
sbcl --non-interactive --eval "(ql:update-all-dists)"
```

**Comment by codmccabe** [comment]
I don't know if you want me to keep posting here, but have done that:
```
~/GitHub$ cd maxima-jupyter/
~/GitHub/maxima-jupyter$ git pull
Already up to date.
~/GitHub/maxima-jupyter$ sbcl --non-interactive --eval "(ql:update-all-dists)"
This is SBCL 2.0.1.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
1 dist to check.
You already have the latest version of "quicklisp": 2021-06-30.
```

I just don't know enough about Lisp to figure it out :(

**Comment by yitzchak** [comment]
Try reinstalling the kernel afterward.

**Comment by codmccabe** [comment]
I got it to install on maxima, but now when I run jupyter notebook I get the 

```
caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "RENDER" not found in the JUPYTER package.
;   
;       Line: 81, Column: 25, File-Position: 2201
```
Sorry, I have tried doing it so many different ways I am sure I have screwed up the install script. I'll just go back to LyX.

**Comment by yitzchak** [comment]
You have got some old maxima-jupyter code someplace. What OS are you using?

**Comment by codmccabe** [comment]
> You have got some old maxima-jupyter code someplace. What OS are you using?

Linux mint 20.1

**Comment by yitzchak** [comment]
Assuming you did a user based installation, then remove everything in `~/.local/share/maxima-jupyter` and then redo your installation.
```
$ maxima
Maxima 5.43.0 http://maxima.sourceforge.net
using Lisp SBCL 1.5.5
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) load("load-maxima-jupyter.lisp");
(%i2) jupyter_install();
```

**Comment by codmccabe** [comment]
I am really sorry for wasting time, it worked by doing what you said. Thank you so much for your help and what you do for the project.

**Comment by yitzchak** [comment]
No worries! Glad you got it working.
